### PR TITLE
Rename `quickwit.json` to `metastore.json`

### PR DESCRIPTION
**Pull request by guilload**
### Description
Rename `quickwit.json` to `metastore.json`. Something we discussed with @fmassot. WDYT @fulmicoton?

### CODE REVIEW

**Comment by PSeitz** [comment]
I think that's better since quickwit.json doesn't tell anything

**Comment by fulmicoton** [comment]
I prefer quickwit.json but I don't care all that much.

**Review by fulmicoton — APPROVED** [review]

**Comment by guilload** [comment]
> I prefer quickwit.json but I don't care all that much.

We also wanted to avoid any confusion with `quickwit.yaml`.

**Comment by fulmicoton** [comment]
Ah yes, Metastore.json is much better

**Pull request merged**
