### PR TITLE
Avoid panic and log a warning when a node join the cluster with an id…

### LINKED ISSUE #962: Prevent a node with a `node-id` already present in a cluster to join in and add understandable logs
Currently, if you create a cluster with 2 searchers with same `node-id`, one node will exit with the following log:

```
thread 'tokio-runtime-worker' panicked at 'Could not find this instance as registered member', quickwit-swim/src/membership.rs:45:9
```

### PR DESCRIPTION
**Pull request by fmassot**
… already taken by a member.

Fix #962

It's tested locally but clearly it's hard to know what is really happening.....

### How was this PR tested?
I tested it locally with 3 searcher nodes. Two with same node id and one with a different. No panic and it show logs like this:

```
2021-12-23T18:04:22.615Z  INFO quickwit_cluster::cluster: Create new cluster. node_id="searcher-1" listen_addr=127.0.0.1:7280
2021-12-23T18:04:22.615Z  INFO quickwit_cluster::cluster: Adding peer node. self_addr=127.0.0.1:7280 peer_addr=127.0.0.1:7290
2021-12-23T18:04:22.616Z  INFO quickwit_serve: Searcher ready to accept requests at http://127.0.0.1:7280/
2021-12-23T18:04:22.616Z  INFO quickwit_serve::rest: Starting REST service. rest_addr=127.0.0.1:7280
2021-12-23T18:04:22.616Z  INFO quickwit_serve::grpc: Start gRPC service. grpc_addr=127.0.0.1:7281
2021-12-23T18:04:25.626Z  WARN quickwit_swim::state: Cannot add a member with a node-id `searcher-1` already present in the cluster.
2021-12-23T18:05:41.876Z  INFO quickwit_cluster::cluster: Joined. node_id="searcher-3" remote_host=Some(127.0.0.1:7300)
```

### CODE REVIEW

**Comment by fmassot** [comment]
Little improvement was made. I still do not panic if same node id is detected. The panic is really ugly as it does not shut down the cluster but just terminates the cluster event loop.

I like the current solution because it is spammy, each time the faulty node will try to join the cluster and will be rejected.
This leads to the following logs:

```
2021-12-23T21:57:02.266Z  INFO quickwit_cluster::cluster: Create new cluster. node_id="searcher-1" listen_addr=127.0.0.1:7280
2021-12-23T21:57:02.266Z  INFO quickwit_cluster::cluster: Adding peer node. self_addr=127.0.0.1:7280 peer_addr=127.0.0.1:7290
2021-12-23T21:57:02.266Z  INFO quickwit_cluster::cluster: Adding peer node. self_addr=127.0.0.1:7280 peer_addr=127.0.0.1:7300
2021-12-23T21:57:02.267Z  INFO quickwit_serve: Searcher ready to accept requests at http://127.0.0.1:7280/
2021-12-23T21:57:02.267Z  INFO quickwit_serve::rest: Starting REST service. rest_addr=127.0.0.1:7280
2021-12-23T21:57:02.267Z  INFO quickwit_serve::grpc: Start gRPC service. grpc_addr=127.0.0.1:7281
2021-12-23T21:57:06.682Z  INFO quickwit_cluster::cluster: Joined. node_id="searcher-2" remote_host=Some(127.0.0.1:7290)
2021-12-23T21:57:09.302Z ERROR quickwit_swim::state: Cannot add a member with a node-id `searcher-1` already present in the cluster.
2021-12-23T21:57:10.305Z ERROR quickwit_swim::state: Cannot add a member with a node-id `searcher-1` already present in the cluster.
2021-12-23T21:57:11.306Z ERROR quickwit_swim::state: Cannot add a member with a node-id `searcher-1` already present in the cluster.
2021-12-23T21:57:12.311Z ERROR quickwit_swim::state: Cannot add a member with a node-id `searcher-1` already present in the cluster.
2021-12-23T21:57:13.313Z ERROR quickwit_swim::state: Cannot add a member with a node-id `searcher-1` already present in the cluster.
2021-12-23T21:57:14.319Z ERROR quickwit_swim::state: Cannot add a member with a node-id `searcher-1` already present in the cluster
```

You will see the same logs on other nodes if the faulty server is listed as a peer.

**Review by fulmicoton — APPROVED** [review]
Awesome. It has bitten me in the past too.

**Comment by fmassot** [comment]
@guilload I think this is ok in the short term before switching to scuttlebutt, ok for you?

**Comment by guilload** [comment]
> @guilload I think this is ok in the short term before switching to scuttlebutt, ok for you?

Yes.

**Pull request merged**
