### PR TITLE
Create partition id from canonical filepath.

### LINKED ISSUE #1049: Second start of an indexer after a file source has been completely indexed trigger an error
## Steps to reproduce
First run
```bash
cargo r index create --index-config ./config/tutorials/wikipedia/index-config.yaml --config ./config/quickwit.yaml --overwrite
curl -o wiki-articles-10000.json https://quickwit-datasets-public.s3.amazonaws.com/wiki-articles-10000.json
cargo r source add --index wikipedia --source wikipedia-source --type file --params '{"filepath":"wiki-articles-10000.json"}'
cargo r service run indexer --config=./config/quickwit.yaml --indexes Wikipedia
```

Wait for the indexer to finish indexing, stop it and restart
```
cargo r service run indexer --config=./config/quickwit.yaml --indexes wikipedia
```

## Reason

This is coming from the fact that:
- we are creating checkpoint from the canonical path
- we are initializing the FileSource with the non-canonical path. And thus we are doomed to restart indexing from checkpoint 0.

## Possible fixe

Use canonical path in both places.

### Logs

```
cargo r service run indexer --config=./config/quickwit.yaml --indexes wikipedia
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
     Running `target/debug/quickwit service run indexer --config=./config/quickwit.yaml --indexes wikipedia`
2022-01-08T19:14:58.024Z  INFO quickwit: version="0.1.0" commit="4108cd3"
2022-01-08T19:14:58.025Z  WARN quickwit_config::config: Seed list is empty.
2022-01-08T19:14:58.025Z  INFO quickwit_cli: Loaded Quickwit config. config_uri=file:///Users/fmassot/Documents/quickwit/repos/quickwit-2/config/quickwit.yaml config=QuickwitConfig { version: 0, node_id: "node-proud-pE9m", listen_address: "127.0.0.1", rest_listen_port: 7280, peer_seeds: [], metastore_uri: "file:///Users/fmassot/Documents/quickwit/repos/quickwit-2/qwdata/indexes", default_index_root_uri: "file:///Users/fmassot/Documents/quickwit/repos/quickwit-2/qwdata/indexes", data_dir_path: "./qwdata", indexer_config: IndexerConfig { split_store_max_num_bytes: Byte(100000000000), split_store_max_num_splits: 1000 }, searcher_config: SearcherConfig { fast_field_cache_capacity: Byte(1000000000), split_footer_cache_capacity: Byte(500000000), max_num_concurrent_split_streams: 100 }, storage_config: None }
2022-01-08T19:14:58.033Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}: quickwit_indexing::actors::indexing_pipeline: spawn-indexing-pipeline root_dir=./qwdata/indexing/wikipedia/wikipedia-source merge_policy=StableMultitenantWithTimestampMergePolicy { demux_enabled: false, demux_factor: 8, demux_field_name: None, min_level_num_docs: 100000, merge_enabled: true, merge_factor: 10, max_merge_factor: 12, split_num_docs_target: 10000000 }
2022-01-08T19:14:58.033Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=GarbageCollector}: quickwit_indexing::actors::garbage_collector: garbage-collect-operation
2022-01-08T19:14:58.151Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Indexer}:{msg_id=2}: quickwit_indexing::actors::indexer: new-split split_id=01FRXHV1VVY8YK1DA3C9YZEVMA
2022-01-08T19:14:58.380Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=FileSource}:{msg_id=22}: quickwit_indexing::source::file_source: EOF
2022-01-08T19:14:58.398Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=FileSource}: quickwit_actors::async_actor: actor-exit actor_id=FileSource-polished-ecPM exit_status=Success
2022-01-08T19:14:58.598Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Indexer}: quickwit_indexing::actors::indexer: send-to-packager commit_trigger=NoMoreDocs split="01FRXHV1VVY8YK1DA3C9YZEVMA" num_docs=10000
2022-01-08T19:14:58.598Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Indexer}: quickwit_actors::sync_actor: actor-exit actor_id=Indexer-icy-S2i1 exit_status=Success
2022-01-08T19:14:58.598Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Packager}:{msg_id=3 num_splits=1}: quickwit_indexing::actors::packager: start-packaging-splits split_ids=["01FRXHV1VVY8YK1DA3C9YZEVMA"]
2022-01-08T19:14:58.599Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Packager}:{msg_id=3 num_splits=1}: quickwit_indexing::actors::packager: commit-split split_id=01FRXHV1VVY8YK1DA3C9YZEVMA
2022-01-08T19:15:17.511Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Packager}:{msg_id=3 num_splits=1}: quickwit_indexing::actors::packager: create-packaged-split split_id="01FRXHV1VVY8YK1DA3C9YZEVMA"
2022-01-08T19:15:17.516Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Uploader}:{msg_id=99 num_splits=1}: quickwit_indexing::actors::uploader: start-stage-and-store-splits split_ids=["01FRXHV1VVY8YK1DA3C9YZEVMA"]
2022-01-08T19:15:17.516Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Uploader}:{msg_id=99 num_splits=1}: quickwit_indexing::actors::uploader: staging-split split_id="01FRXHV1VVY8YK1DA3C9YZEVMA"
2022-01-08T19:15:17.518Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Uploader}:{msg_id=99 num_splits=1}: quickwit_indexing::actors::uploader: storing-split split_id="01FRXHV1VVY8YK1DA3C9YZEVMA"
2022-01-08T19:15:17.518Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Uploader}:{msg_id=99 num_splits=1}: quickwit_indexing::split_store::indexing_split_store: store-split-remote-start
2022-01-08T19:15:17.721Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Packager}: quickwit_actors::sync_actor: actor-exit actor_id=Packager-green-gwPI exit_status=Success
2022-01-08T19:15:17.874Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Uploader}:{msg_id=99 num_splits=1}: quickwit_indexing::split_store::indexing_split_store: store-split-remote-success split_size_in_megabytes=11 elapsed_secs=0.35549423 throughput_mb_s=30.942837 is_mature=false
2022-01-08T19:15:17.874Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Uploader}:{msg_id=99 num_splits=1}: quickwit_indexing::split_store::indexing_split_store: store-in-cache
2022-01-08T19:15:17.875Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Uploader}:{msg_id=99 num_splits=1}: quickwit_indexing::actors::uploader: success-stage-and-store-splits
2022-01-08T19:15:17.875Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Publisher}:{msg_id=99}: quickwit_indexing::actors::publisher: new-split-start
2022-01-08T19:15:17.875Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Publisher}:{msg_id=99}: quickwit_metastore::checkpoint: delta=∆(/Users/fmassot/Documents/quickwit/repos/quickwit-2/wiki-articles-10000.json:(00000000000000000000..00000000000011252193]) checkpoint=Ckpt(/Users/fmassot/Documents/quickwit/repos/quickwit-2/wiki-articles-10000.json:00000000000011252193)
2022-01-08T19:15:17.875Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Publisher}: quickwit_actors::async_actor: actor-exit actor_id=Publisher-rough-HEqp exit_status=Failure(cause=Failed to publish splits.

Caused by:
    0: Publish checkpoint delta overlaps with the current checkpoint: IncompatibleCheckpointDelta { partition_id: PartitionId("/Users/fmassot/Documents/quickwit/repos/quickwit-2/wiki-articles-10000.json"), current_position: Offset("00000000000011252193"), delta_position_from: Offset("00000000000000000000") }.
    1: IncompatibleChkptDelta at partition: PartitionId("/Users/fmassot/Documents/quickwit/repos/quickwit-2/wiki-articles-10000.json") cur_pos:Offset("00000000000011252193") delta_pos:Offset("00000000000000000000"))
2022-01-08T19:15:17.875Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=MergePlanner}: quickwit_actors::sync_actor: actor-exit actor_id=MergePlanner-wild-Fqrq exit_status=Success
2022-01-08T19:15:17.876Z ERROR {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Publisher}: quickwit_actors::actor: exit activating-kill-switch actor=Publisher-rough-HEqp exit_status=Failure(Failed to publish splits.

Caused by:
    0: Publish checkpoint delta overlaps with the current checkpoint: IncompatibleCheckpointDelta { partition_id: PartitionId("/Users/fmassot/Documents/quickwit/repos/quickwit-2/wiki-articles-10000.json"), current_position: Offset("00000000000011252193"), delta_position_from: Offset("00000000000000000000") }.
    1: IncompatibleChkptDelta at partition: PartitionId("/Users/fmassot/Documents/quickwit/repos/quickwit-2/wiki-articles-10000.json") cur_pos:Offset("00000000000011252193") delta_pos:Offset("00000000000000000000"))
2022-01-08T19:15:17.876Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=GarbageCollector}: quickwit_actors::async_actor: actor-exit actor_id=GarbageCollector-twilight-OYRV exit_status=Killed
2022-01-08T19:15:17.923Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=Uploader}: quickwit_actors::async_actor: actor-exit actor_id=Uploader-divine-DQpX exit_status=Killed
2022-01-08T19:15:17.936Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=MergePackager}: quickwit_actors::sync_actor: actor-exit actor_id=MergePackager-nameless-Wmv0 exit_status=Killed
2022-01-08T19:15:17.954Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=MergeExecutor}: quickwit_actors::sync_actor: actor-exit actor_id=MergeExecutor-silent-kEXq exit_status=Killed
2022-01-08T19:15:18.021Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=MergePublisher}: quickwit_actors::async_actor: actor-exit actor_id=MergePublisher-purple-C31y exit_status=Killed
2022-01-08T19:15:18.021Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=MergeSplitDownloader}: quickwit_actors::async_actor: actor-exit actor_id=MergeSplitDownloader-cool-YBqx exit_status=Killed
2022-01-08T19:15:18.021Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{index=wikipedia gen=0}:{actor=MergeUploader}: quickwit_actors::async_actor: actor-exit actor_id=MergeUploader-winter-GOUN exit_status=Killed
2022-01-08T19:15:18.113Z ERROR {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{msg_id=120}: quickwit_actors::actor_handle: actor-exit-without-success actor="Uploader-divine-DQpX" exit_status=Killed
2022-01-08T19:15:18.113Z ERROR {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{msg_id=120}: quickwit_actors::actor_handle: actor-exit-without-success actor="Publisher-rough-HEqp" exit_status=Failure(Failed to publish splits.

Caused by:
    0: Publish checkpoint delta overlaps with the current checkpoint: IncompatibleCheckpointDelta { partition_id: PartitionId("/Users/fmassot/Documents/quickwit/repos/quickwit-2/wiki-articles-10000.json"), current_position: Offset("00000000000011252193"), delta_position_from: Offset("00000000000000000000") }.
    1: IncompatibleChkptDelta at partition: PartitionId("/Users/fmassot/Documents/quickwit/repos/quickwit-2/wiki-articles-10000.json") cur_pos:Offset("00000000000011252193") delta_pos:Offset("00000000000000000000"))
2022-01-08T19:15:18.114Z ERROR {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{msg_id=120}: quickwit_actors::actor_handle: actor-exit-without-success actor="GarbageCollector-twilight-OYRV" exit_status=Killed
2022-01-08T19:15:18.114Z ERROR {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{msg_id=120}: quickwit_actors::actor_handle: actor-exit-without-success actor="MergeSplitDownloader-cool-YBqx" exit_status=Killed
2022-01-08T19:15:18.114Z ERROR {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{msg_id=120}: quickwit_actors::actor_handle: actor-exit-without-success actor="MergeExecutor-silent-kEXq" exit_status=Killed
2022-01-08T19:15:18.114Z ERROR {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{msg_id=120}: quickwit_actors::actor_handle: actor-exit-without-success actor="MergePackager-nameless-Wmv0" exit_status=Killed
2022-01-08T19:15:18.114Z ERROR {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{msg_id=120}: quickwit_actors::actor_handle: actor-exit-without-success actor="MergeUploader-winter-GOUN" exit_status=Killed
2022-01-08T19:15:18.114Z ERROR {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{msg_id=120}: quickwit_actors::actor_handle: actor-exit-without-success actor="MergePublisher-purple-C31y" exit_status=Killed
2022-01-08T19:15:18.114Z ERROR {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{msg_id=120}: quickwit_indexing::actors::indexing_pipeline: indexing pipeline error. index=wikipedia gen=1 healthy=[] failure_or_unhealthy_actors=["Uploader-divine-DQpX", "Publisher-rough-HEqp", "GarbageCollector-twilight-OYRV", "MergeSplitDownloader-cool-YBqx", "MergeExecutor-silent-kEXq", "MergePackager-nameless-Wmv0", "MergeUploader-winter-GOUN", "MergePublisher-purple-C31y"] success=["FileSource-polished-ecPM", "Indexer-icy-S2i1", "Packager-green-gwPI", "MergePlanner-wild-Fqrq"]
2022-01-08T19:15:19.118Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{msg_id=126}:{index=wikipedia gen=1}: quickwit_indexing::actors::indexing_pipeline: spawn-indexing-pipeline root_dir=./qwdata/indexing/wikipedia/wikipedia-source merge_policy=StableMultitenantWithTimestampMergePolicy { demux_enabled: false, demux_factor: 8, demux_field_name: None, min_level_num_docs: 100000, merge_enabled: true, merge_factor: 10, max_merge_factor: 12, split_num_docs_target: 10000000 }
2022-01-08T19:15:19.123Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{msg_id=126}:{index=wikipedia gen=1}:{actor=GarbageCollector}: quickwit_indexing::actors::garbage_collector: garbage-collect-operation
2022-01-08T19:15:19.228Z  INFO {actor=quickwit_indexing::actors::indexing_server::IndexingServer}:{msg_id=1}::{msg_id=126}:{index=wikipedia gen=1}:{actor=Indexer}:{msg_id=1}: quickwit_indexing::actors::indexer: new-split split_id=01FRXHVPEY0N2V23JK1WBW9F7G
```

### PR DESCRIPTION
**Pull request by fmassot**
Fix #1049.

## Current fix
I just updated the code to use a canonical path when initializing the file source.

## Better fix?

Today we are storing the `FileSource` is storing the `filepath` and the `filepath` can be relative. 
On the other hand, checkpoints are based on the canonical path.

I think this can be confusing. When a user wants to see the list of sources of an index, he will see a relative `filepath`. This can be very strange, and if a user moves the `quickwit-v0.2` install directory and starts the indexing server, this will reindex the file even if it has been already indexed.

### Solution 1
To remain consistent between checkpoints and FileSource, we can use the canonical path everywhere. I would go for that for release 0.2.

### Solution 2
We could use another identifier for the file like the md5 hash. I think we could rethink that when we introduce a file source for cloud storage for example.

### CODE REVIEW

**Comment by fulmicoton** [comment]
Ouch nice catch

**Review by fulmicoton — APPROVED** [review]

**Comment by fmassot** [comment]
@fulmicoton did you see the inconsistency I pointed out? About the fact that we have a source that stores a relative path on one side and a checkpoint that refers to the canonical path on the other side.

**Comment by fulmicoton** [comment]
> We could use another identifier for the file like the md5 hash.

md5 seems like a terrible idea. You would have to read entirely a file to resume indexing
regardless of whether the file has a checkpoint or not...

> To remain consistent between checkpoints and FileSource, we can use the canonical path everywhere. I would go for that for release 0.2.

I think we want canonical. One place where we could relax this constraint is the user input, in which, assuming we did the proper checks on add_source, we could resolve `relative_path` to `absolute_path`.

**Comment by fmassot** [comment]
> You would have to read entirely a file to resume indexing regardless of whether the file has a checkpoint or not...

arf indeed... 

> I think we want canonical. One place where we could relax this constraint is the user input, in which, assuming we did the proper checks on add_source, we could resolve relative_path to absolute_path.

Yes, I had also that in mind, it's ok if the path is relative in input.

**Comment by fmassot** [comment]
Obsolete PR, replaced by #1058

**Pull request closed without merging**
