### PR TITLE
Doc update

### PR DESCRIPTION
**Pull request by fmassot**
Dearest Reviewer,

I noticed a missing paren. I could not let that stand.

Thanks for the amazing code. I am enjoying reading it.

Becker

### CODE REVIEW

**Comment by fmassot** [comment]
@sbeckeriv can you please sign our contributor license agreement?

**Comment by sbeckeriv** [comment]
@fmassot done. thanks. Mighty kind to take the pull request instead of updating the docs directly.

**Review by evanxg852000 — APPROVED** [review]

**Comment by fmassot** [comment]
@sbeckeriv can you update your branch?

**Comment by fmassot** [comment]
thanks @sbeckeriv !

**Pull request merged**
